AWSTemplateFormatVersion: 2010-09-09
Description: >-
    aws-lambda
Transform:
    - AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
    # Each Lambda function is defined by properties:
    # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

    # This is a Lambda function config associated with the source code: get-all-items.js
    apiFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: src/handlers/api.handler
            Description: A simple example includes a HTTP get method
            Events:
                GetApi:
                    Type: Api
                    Properties:
                        Path: /
                        Method: GET
                PostApi:
                    Type: Api
                    Properties:
                        Path: /
                        Method: POST
                PutAPI:
                    Type: Api
                    Properties:
                        Path: /
                        Method: PUT
Outputs:
    WebEndpoint:
        Description: API Gateway endpoint URL for Prod stage
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        LoggingConfig:
            LogFormat: JSON
        Runtime: nodejs20.x
        Architectures:
            - x86_64
        MemorySize: 128
        Timeout: 100
        Environment:
            Variables:
                HIGHLIGHT_PROJECT_ID: '1'
