export const authorDescription: string
export const authorDetails: string
export const authorDiv: string
export const avatar: string
export const blogContainer: string
export const blogImageContainer: string
export const blogPost: string
export const blogPostSmall: string
export const blogSection: string
export const blogText: string
export const bodyText: string
export const cardImage: string
export const cardSection: string
export const codeBlock: string
export const codeInline: string
export const copyOnDark: string
export const dateDiv: string
export const headerSection: string
export const mainBlogPadding: string
export const mainImage: string
export const otherArticlesHeader: string
export const postBody: string
export const postBodyDivider: string
export const postBodyTop: string
export const postDateDiv: string
export const postTagDiv: string
export const selectedTag: string
export const suggestedBlogPost: string
export const suggestedPost: string
export const suggestedPostDiv: string
export const suggestedPostTitle: string
export const tagContainer: string
export const tagDiv: string
export const tagHeader: string
export const tagSortTitle: string
export const youtubeEmbed: string
