export const dropdownEmail: string
export const dropdownHandler: string
export const dropdownInner: string
export const dropdownLogout: string
export const dropdownLogoutText: string
export const dropdownMenu: string
export const dropdownName: string
export const icon: string
export const newOrgDiv: string
export const orgItem: string
export const orgNameText: string
export const orgNameWrapper: string
export const orgText: string
export const plusIcon: string
export const selectedOrgItem: string
export const workspaceIcon: string
export const workspaceIconMiniWrapper: string
