export const dropdownGray: string
export const dropdownHandler: string
export const dropdownInner: string
export const dropdownMenu: string
export const icon: string
export const labelItem: string
export const labelNameText: string
export const labelText: string
export const overlay: string
export const placeholder: string
