export const annualToggleAltText: string
export const annualToggleBox: string
export const annualToggleText: string
export const billingIssues: string
export const billingPlanCardWrapper: string
export const contact: string
export const detailsCard: string
export const detailsCardTitle: string
export const header: string
export const infoTooltip: string
export const invoiceFailedBell: string
export const invoiceFailedCard: string
export const invoiceFailedContainer: string
export const invoiceFailedHeader: string
export const invoiceFailedUpdatePayment: string
export const overageToggle: string
export const portalButton: string
export const portalButtonContainer: string
export const portalButtonIcon: string
export const retentionPeriodBox: string
export const subTitle: string
export const subtotal: string
export const titleContainer: string
export const toggleControls: string
export const unlimitedMembersButton: string
export const unlimitedMembersCard: string
export const unlimitedMembersContainer: string
export const unlimitedMembersHeader: string
export const unlimitedMembersIcon: string
export const workspaceTabs: string
