export const email: string
export const header: string
export const memberCard: string
export const memberCardWrapper: string
export const membersTitle: string
export const membersTitleContainer: string
export const name: string
export const removeTeamMemberButton: string
export const role: string
export const subTitle: string
export const titleContainer: string
export const userDetails: string
