export const downIndicator: string
export const icon: string
export const popover: string
export const popoverContent: string
export const popoverTitle: string
export const shortcutButton: string
export const speedButton: string
export const speedControlContainer: string
export const speedText: string
