export const copyrightText: string
export const footer: string
export const footerBottom: string
export const footerBottomMobile: string
export const footerList: string
export const footerListLight: string
export const footerTitle: string
export const socialDiv: string
export const socialDivLight: string
export const socialIcon: string
export const status: string
export const statusCircle: string
export const statusDiv: string
