CREATE TABLE IF NOT EXISTS sessions (
    ID Int64,
    CreatedAt DateTime64(6),
    UpdatedAt DateTime64(6),
    SecureID String,
    Identified Bool,
    Fingerprint Int32,
    Identifier String,
    ProjectID Int32,
    City String,
    Country String,
    OSName String,
    OSVersion String,
    BrowserName String,
    BrowserVersion String,
    Processed Bool,
    HasRageClicks Bool,
    HasErrors Bool,
    Length Int64,
    ActiveLength Int64,
    FieldKeys Array(String),
    FieldKeyValues Array(String),
    Environment String,
    AppVersion String,
    FirstTime Bool,
    Viewed Bool,
    WithinBillingQuota Bool,
    EventCounts String,
    PagesVisited Nullable(Int32),
    Excluded Bool,
    ViewedByAdmins Array(Int32),
    Normalness Float64
) ENGINE = ReplacingMergeTree(UpdatedAt)
ORDER BY (ProjectID, CreatedAt, ID);