ALTER TABLE traces_sampling_new_mv
MODIFY QUERY
SELECT `Timestamp`,
    `UUID`,
    `TraceId`,
    `SpanId`,
    `ParentSpanId`,
    `ProjectId`,
    `SecureSessionId`,
    `TraceState`,
    `SpanName`,
    `SpanKind`,
    `Duration`,
    `ServiceName`,
    `ServiceVersion`,
    `TraceAttributes`,
    `StatusCode`,
    `StatusMessage`,
    `Events.Timestamp`,
    `Events.Name`,
    `Events.Attributes`,
    `Links.TraceId`,
    `Links.SpanId`,
    `Links.TraceState`,
    `Links.Attributes`,
    `Environment`,
    `HasErrors`
FROM traces;
ALTER TABLE traces DROP COLUMN IF EXISTS HttpResponseBody,
    DROP COLUMN IF EXISTS HttpRequestBody,
    DROP COLUMN IF EXISTS HttpUrl,
    DROP COLUMN IF EXISTS HighlightKey,
    MODIFY COLUMN IF EXISTS HighlightType MATERIALIZED TraceAttributes ['highlight.type'],
    DROP COLUMN IF EXISTS HttpAttributes,
    DROP COLUMN IF EXISTS ProcessAttributes,
    DROP COLUMN IF EXISTS OsAttributes,
    DROP COLUMN IF EXISTS TelemetryAttributes,
    DROP COLUMN IF EXISTS WsAttributes,
    DROP COLUMN IF EXISTS EventAttributes,
    DROP COLUMN IF EXISTS DbAttributes;
ALTER TABLE traces_sampling_new DROP COLUMN IF EXISTS HttpResponseBody,
    DROP COLUMN IF EXISTS HttpRequestBody,
    DROP COLUMN IF EXISTS HttpUrl,
    DROP COLUMN IF EXISTS HighlightKey,
    MODIFY COLUMN IF EXISTS HighlightType MATERIALIZED TraceAttributes ['highlight.type'],
    DROP COLUMN IF EXISTS HttpAttributes,
    DROP COLUMN IF EXISTS ProcessAttributes,
    DROP COLUMN IF EXISTS OsAttributes,
    DROP COLUMN IF EXISTS TelemetryAttributes,
    DROP COLUMN IF EXISTS WsAttributes,
    DROP COLUMN IF EXISTS EventAttributes,
    DROP COLUMN IF EXISTS DbAttributes;