ALTER TABLE logs DROP COLUMN IF EXISTS Embedding;
ALTER TABLE logs DROP COLUMN IF EXISTS EmbeddingModel;
ALTER TABLE logs DROP COLUMN IF EXISTS LogGroupId;
ALTER TABLE logs_sampling DROP COLUMN IF EXISTS Embedding;
ALTER TABLE logs_sampling DROP COLUMN IF EXISTS EmbeddingModel;
ALTER TABLE logs_sampling DROP COLUMN IF EXISTS LogGroupId;