CREATE TABLE IF NOT EXISTS traces_sampling_new (
    `Timestamp` DateTime64(9),
    `UUID` UUID,
    `TraceId` String,
    `SpanId` String,
    `ParentSpanId` String,
    `ProjectId` UInt32,
    `SecureSessionId` String,
    `TraceState` String,
    `SpanName` LowCardinality(String),
    `SpanKind` LowCardinality(String),
    `Duration` Int64,
    `ServiceName` LowCardinality(String),
    `ServiceVersion` String,
    `TraceAttributes` Map(LowCardinality(String), String),
    `StatusCode` LowCardinality(String),
    `StatusMessage` String,
    `Events.Timestamp` Array(DateTime64(9)),
    `Events.Name` Array(LowCardinality(String)),
    `Events.Attributes` Array(Map(LowCardinality(String), String)),
    `Links.TraceId` Array(String),
    `Links.SpanId` Array(String),
    `Links.TraceState` Array(String),
    `Links.Attributes` Array(Map(LowCardinality(String), String)),
    `Environment` String,
    `HasErrors` Bool,
    `MetricName` Nullable(String) MATERIALIZED (Events.Attributes [1]) ['metric.name'],
    `MetricValue` Nullable(Float64) MATERIALIZED toFloat64OrNull((Events.Attributes [1]) ['metric.value']),
    `HighlightType` String MATERIALIZED TraceAttributes ['highlight.type']
) ENGINE = MergeTree PARTITION BY toStartOfDay(Timestamp)
ORDER BY (
        toStartOfHour(Timestamp),
        ProjectId,
        farmHash64(TraceId)
    ) SAMPLE BY farmHash64(TraceId) TTL toDateTime(Timestamp) + toIntervalDay(30) SETTINGS index_granularity = 8192,
    min_rows_for_wide_part = 0,
    min_bytes_for_wide_part = 0,
    ttl_only_drop_parts = 1,
    min_bytes_for_full_part_storage = 4294967296,
    max_bytes_to_merge_at_min_space_in_pool = 10485760,
    number_of_free_entries_in_pool_to_lower_max_size_of_merge = 6;
CREATE MATERIALIZED VIEW IF NOT EXISTS traces_sampling_new_mv TO traces_sampling_new (
    `Timestamp` DateTime64(9),
    `UUID` UUID,
    `TraceId` String,
    `SpanId` String,
    `ParentSpanId` String,
    `ProjectId` UInt32,
    `SecureSessionId` String,
    `TraceState` String,
    `SpanName` LowCardinality(String),
    `SpanKind` LowCardinality(String),
    `Duration` Int64,
    `ServiceName` LowCardinality(String),
    `ServiceVersion` String,
    `TraceAttributes` Map(LowCardinality(String), String),
    `StatusCode` LowCardinality(String),
    `StatusMessage` String,
    `Events.Timestamp` Array(DateTime64(9)),
    `Events.Name` Array(LowCardinality(String)),
    `Events.Attributes` Array(Map(LowCardinality(String), String)),
    `Links.TraceId` Array(String),
    `Links.SpanId` Array(String),
    `Links.TraceState` Array(String),
    `Links.Attributes` Array(Map(LowCardinality(String), String))
) AS
SELECT *
FROM traces;