export const addContainer: string;
export const alertConfigurationCard: string;
export const channelSelect: string;
export const frequencyContainer: string;
export const lookbackPeriodSelect: string;
export const notFoundMessage: string;
export const saveButton: string;
export const selectMessage: string;
export const title: string;
