export const actionsContainer: string
export const addContainer: string
export const alertConfigurationCard: string
export const channelSelect: string
export const footer: string
export const frequencyContainer: string
export const lookbackPeriodSelect: string
export const notFoundContentEmail: string
export const notFoundMessage: string
export const saveButton: string
export const subTitle: string
