export const bucketMark: string
export const eventHistogram: string
export const eventTrack: string
export const inactivityPeriod: string
export const inactivityPeriodMask: string
export const inactivityPeriodPlayed: string
export const liveProgressBar: string
export const liveShimmer: string
export const progressBar: string
export const progressBarContainer: string
export const separator: string
export const sessionMonitor: string
export const timeAxis: string
export const timelineContainer: string
export const timelineIndicatorsContainer: string
export const timeTick: string
export const timeTickMajor: string
export const timeTickMark: string
export const timeTickMid: string
export const timeTickMinor: string
