export const bucketMark: string
export const eventHistogram: string
export const eventTrack: string
export const progressBar: string
export const progressBarContainer: string
export const progressMonitor: string
export const section: string
export const separator: string
export const timeAxis: string
export const timeIndicator: string
export const timeIndicatorHair: string
export const timeIndicatorTop: string
export const timelineContainer: string
export const timelineIndicatorsContainer: string
export const timeMarker: string
export const timeTick: string
export const timeTickMajor: string
export const timeTickMid: string
export const timeTickMinor: string
export const zoomArea: string
