export const accountIcon: string
export const accountIconWrapper: string
export const avatarWrapper: string
export const dropdownEmail: string
export const dropdownInner: string
export const dropdownLogout: string
export const dropdownLogoutText: string
export const dropdownMenu: string
export const dropdownMyAccount: string
export const dropdownName: string
export const logoutIcon: string
export const userCopy: string
export const userInfoWrapper: string
