export const card: string;
export const cardForm: string;
export const cardFormActionsContainer: string;
export const cardHeader: string;
export const cardSubHeader: string;
export const interactable: string;
export const noPadding: string;
export const noTitleBottomMargin: string;
export const titleContainer: string;
