FROM golang:alpine as backend-builder
RUN apk update && apk add git
RUN mkdir /build-backend
WORKDIR /build-backend
COPY ./backend .
RUN go mod download
RUN GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o /bin/backend

FROM alpine
WORKDIR /root/
COPY --from=backend-builder /bin/backend /bin/backend

CMD ["/bin/backend"]
