export const activeButton: string
export const button: string
export const currentTime: string
export const leftClickActionName: string
export const leftSelection: string
export const liveUserStatus: string
export const minorButton: string
export const moveRight: string
export const popoverCmdShortcut: string
export const section: string
export const settingsButton: string
export const settingsContainer: string
export const settingsOptionShortcut: string
export const settingsPopoverOverlay: string
export const smallButton: string
