export const groupHeading: string;
export const hideSearchIcon: string;
export const optionLabelContainer: string;
export const optionLabelName: string;
export const optionLabelType: string;
export const quickSearchSelect: string;
export const searchIcon: string;
export const select: string;
export const typeIcon: string;
