export const checkboxUnselected: string
export const commonInputWrapper: string
export const datePicker: string
export const fill: string
export const icon: string
export const iconWrapper: string
export const searchInput: string
export const select: string
export const selectWithIconContainer: string
export const subTitle: string
export const switchSpan: string
