export const actionsContainer: string
export const checkIcon: string
export const downIcon: string
export const dropdownHandler: string
export const modalSubTitle: string
export const modalWrapper: string
export const newSearchDiv: string
export const noSegmentsText: string
export const plusIcon: string
export const segmentAction: string
export const segmentItem: string
export const segmentItemWrapper: string
export const segmentNameText: string
export const segmentPickerInner: string
export const segmentPickerMenu: string
export const segmentText: string
export const segmentUnselected: string
export const trashIcon: string
