# options for analysis running
run:
    timeout: 2m
    skip-dirs:
        - private-graph/graph/generated
        - public-graph/graph/generated

# output configuration options
output:
    # sorts results by: filepath, line and column
    sort-results: true

linters:
    # enable all linters
    enable:
        - errcheck
        - gosimple
        - govet
        - ineffassign
        - staticcheck
        - typecheck
        - unused
        - depguard
        - exhaustruct

# all available settings of specific linters
linters-settings:
    staticcheck:
        checks: ['all']

    exhaustruct:
        include:
            - 'backend/alerts'

    depguard:
        list-type: denylist
        include-go-root: true
        packages:
            - log

        packages-with-error-message:
            # specify an error message to output when a denylist package is used
            - log: 'logging is allowed only by github.com/sirupsen/logrus'
