# options for analysis running
run:
  timeout: 2m
  skip-dirs:
    - private-graph/graph/generated
    - public-graph/graph/generated
    - highlight-go

# output configuration options
output:
  # sorts results by: filepath, line and column
  sort-results: true

linters:
  # enable all linters
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck

# all available settings of specific linters
linters-settings:
  gosimple:
    # Select the Go version to target. The default is '1.13'.
    go: "1.14"

  staticcheck:
    # Select the Go version to target. The default is '1.13'.
    go: "1.14"
    checks: [ "all" ]

  stylecheck:
    # Select the Go version to target. The default is '1.13'.
    go: "1.14"

  unused:
    # Select the Go version to target. The default is '1.13'.
    go: "1.14"
