# options for analysis running
run:
    timeout: 2m
    skip-dirs:
        - private-graph/graph/generated
        - public-graph/graph/generated
        - highlight-go

# output configuration options
output:
    # sorts results by: filepath, line and column
    sort-results: true

linters:
    # enable all linters
    enable:
        - errcheck
        - gosimple
        - govet
        - ineffassign
        - staticcheck
        - typecheck
        - unused
        - depguard

# all available settings of specific linters
linters-settings:
    gosimple:
        go: '1.19'

    staticcheck:
        go: '1.19'
        checks: ['all']

    stylecheck:
        go: '1.19'

    unused:
        go: '1.19'

    depguard:
        list-type: blacklist
        include-go-root: true
        packages:
            - errors
            - log

        packages-with-error-message:
            # specify an error message to output when a blacklisted package is used
            - errors: 'error handling is allowed only by github.com/pkg/errors'
            - log: 'logging is allowed only by github.com/sirupsen/logrus'
