export const authorSection: string
export const card: string
export const container: string
export const description: string
export const grid: string
export const header: string
export const imageContainer: string
export const tagPage: string
export const tags: string
export const title: string
