export const changelogButton: string
export const changelogContainer: string
export const icon: string
export const miniRow: string
export const miniSidebarIconWrapper: string
export const selected: string
export const settingsDivider: string
export const sideBar: string
export const staticSidebarWrapper: string
