export const anchorFeature: string
export const anchorFeaturePricing: string
export const anchorHead: string
export const anchorImage: string
export const anchorTitle: string
export const billingButton: string
export const billingCopy: string
export const billingCycleText: string
export const billingWidget: string
export const billingWidgetButtons: string
export const buttonContainer: string
export const carouselDiv: string
export const checkmark: string
export const circleButton: string
export const collapseInner: string
export const configColumn: string
export const customerSection: string
export const desktopFeaturesSection: string
export const desktopPrice: string
export const desktopSessionCredits: string
export const desktopSessionCreditsEnterprise: string
export const desktopTierSection: string
export const desktopTopTier: string
export const discountPill: string
export const discountPillVisible: string
export const dotSelected: string
export const expanded: string
export const faqDivider: string
export const faqLeftContent: string
export const faqRow: string
export const faqRowClickable: string
export const faqSection: string
export const featureDivider: string
export const featureKey: string
export const featureKeyDivider: string
export const featureKeys: string
export const featureName: string
export const featureSet: string
export const leftButton: string
export const mobileBillingWrapper: string
export const mobileCarousel: string
export const mobileFeatureDivider: string
export const mobileFeatureHeader: string
export const mobileFeatureInner: string
export const mobileFeatureName: string
export const mobileFeatureRow: string
export const mobileFeaturesSection: string
export const mobileFeaturesWrapper: string
export const mobileNotSelectedPlan: string
export const mobilePricingButton: string
export const mobileSessionCredits: string
export const mobileTier: string
export const mobileTierCard: string
export const mobileTierCarousel: string
export const mobileTierDot: string
export const mobileTierDots: string
export const mobileTiers: string
export const mobileTierSectionWrapper: string
export const mobileTierTop: string
export const mobileTierWrapper: string
export const moneySign: string
export const mostPopular: string
export const mostPopularMobile: string
export const mostPopularTierColumn: string
export const mostPopularTierColumnMobile: string
export const price: string
export const priceDuration: string
export const priceNum: string
export const pricingBreakdown: string
export const pricingButton: string
export const pricingTable: string
export const pricingTitle: string
export const question: string
export const questionDescription: string
export const rightButton: string
export const secondaryAnchor: string
export const sectionSubtitle: string
export const selected: string
export const startTrial: string
export const tableBody: string
export const tableCard: string
export const tierColumn: string
export const tierHeader: string
export const tierInfo: string
export const tierName: string
export const tierPrice: string
export const tierWrapper: string
export const timeIndicator: string
export const titleSection: string
export const yellowText: string
