package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"
	"fmt"
	"time"

	"github.com/DmitriyVTitov/size"
	"github.com/google/uuid"
	"github.com/highlight-run/highlight/backend/hlog"
	kafkaqueue "github.com/highlight-run/highlight/backend/kafka-queue"
	"github.com/highlight-run/highlight/backend/model"
	generated1 "github.com/highlight-run/highlight/backend/public-graph/graph/generated"
	customModels "github.com/highlight-run/highlight/backend/public-graph/graph/model"
	"github.com/openlyinc/pointy"
	e "github.com/pkg/errors"
	log "github.com/sirupsen/logrus"
	"gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer"
)

// InitializeSession is the resolver for the initializeSession field.
func (r *mutationResolver) InitializeSession(ctx context.Context, sessionSecureID string, organizationVerboseID string, enableStrictPrivacy bool, enableRecordingNetworkContents bool, clientVersion string, firstloadVersion string, clientConfig string, environment string, appVersion *string, serviceName string, fingerprint string, clientID string, networkRecordingDomains []string, disableSessionRecording *bool) (*customModels.InitializeSessionResponse, error) {
	s, _ := tracer.StartSpanFromContext(ctx, "InitializeSession", tracer.ResourceName("gql.initializeSession"))
	s.SetTag("secure_id", sessionSecureID)
	s.SetTag("client_version", clientVersion)
	s.SetTag("firstload_version", firstloadVersion)
	defer s.Finish()
	acceptLanguageString := ctx.Value(model.ContextKeys.AcceptLanguage).(string)
	userAgentString := ctx.Value(model.ContextKeys.UserAgent).(string)
	ip := ctx.Value(model.ContextKeys.IP).(string)

	projectID, err := model.FromVerboseID(organizationVerboseID)
	if err != nil {
		log.WithContext(ctx).Errorf("An unsupported verboseID was used: %s, %s", organizationVerboseID, clientConfig)
	} else {
		err = r.ProducerQueue.Submit(ctx, sessionSecureID, &kafkaqueue.Message{
			Type: kafkaqueue.InitializeSession,
			InitializeSession: &kafkaqueue.InitializeSessionArgs{
				SessionSecureID:                sessionSecureID,
				CreatedAt:                      time.Now(),
				ProjectVerboseID:               organizationVerboseID,
				EnableStrictPrivacy:            enableStrictPrivacy,
				EnableRecordingNetworkContents: enableRecordingNetworkContents,
				ClientVersion:                  clientVersion,
				FirstloadVersion:               firstloadVersion,
				ClientConfig:                   clientConfig,
				Environment:                    environment,
				AppVersion:                     appVersion,
				ServiceName:                    serviceName,
				Fingerprint:                    fingerprint,
				UserAgent:                      userAgentString,
				AcceptLanguage:                 acceptLanguageString,
				IP:                             ip,
				ClientID:                       clientID,
				NetworkRecordingDomains:        networkRecordingDomains,
				DisableSessionRecording:        disableSessionRecording,
			},
		})
		if err == nil {
			err = r.Redis.SetIsPendingSession(ctx, sessionSecureID, true)
		}
		if err == nil {
			exceeded, err := r.Redis.IsBillingQuotaExceeded(ctx, projectID, model.PricingProductTypeSessions)
			if err == nil && exceeded != nil && *exceeded {
				err = e.New(string(customModels.PublicGraphErrorBillingQuotaExceeded))
			}
		}
	}

	hlog.Incr("gql.initializeSession.count", []string{fmt.Sprintf("success:%t", err == nil), fmt.Sprintf("project_verbose_id:%q", organizationVerboseID), fmt.Sprintf("project_id:%d", projectID), fmt.Sprintf("secure_id:%s", sessionSecureID), fmt.Sprintf("firstload_version:%s", firstloadVersion), fmt.Sprintf("client_version:%s", clientVersion)}, 1)
	s.SetTag("success", err == nil)

	return &customModels.InitializeSessionResponse{
		SecureID:  sessionSecureID,
		ProjectID: projectID,
	}, err
}

// IdentifySession is the resolver for the identifySession field.
func (r *mutationResolver) IdentifySession(ctx context.Context, sessionSecureID string, userIdentifier string, userObject interface{}) (string, error) {
	err := r.ProducerQueue.Submit(ctx, sessionSecureID, &kafkaqueue.Message{
		Type: kafkaqueue.IdentifySession,
		IdentifySession: &kafkaqueue.IdentifySessionArgs{
			SessionSecureID: sessionSecureID,
			UserIdentifier:  userIdentifier,
			UserObject:      userObject,
		},
	})
	return sessionSecureID, err
}

// AddSessionProperties is the resolver for the addSessionProperties field.
func (r *mutationResolver) AddSessionProperties(ctx context.Context, sessionSecureID string, propertiesObject interface{}) (string, error) {
	err := r.ProducerQueue.Submit(ctx, sessionSecureID, &kafkaqueue.Message{
		Type: kafkaqueue.AddSessionProperties,
		AddSessionProperties: &kafkaqueue.AddSessionPropertiesArgs{
			SessionSecureID:  sessionSecureID,
			PropertiesObject: propertiesObject,
		},
	})
	return sessionSecureID, err
}

// PushPayload is the resolver for the pushPayload field.
func (r *mutationResolver) PushPayload(ctx context.Context, sessionSecureID string, events customModels.ReplayEventsInput, messages string, resources string, webSocketEvents *string, errors []*customModels.ErrorObjectInput, isBeacon *bool, hasSessionUnloaded *bool, highlightLogs *string, payloadID *int) (int, error) {
	if payloadID == nil {
		payloadID = pointy.Int(0)
	}

	err := r.ProducerQueue.Submit(ctx, sessionSecureID, &kafkaqueue.Message{
		Type: kafkaqueue.PushPayload,
		PushPayload: &kafkaqueue.PushPayloadArgs{
			SessionSecureID:    sessionSecureID,
			Events:             events,
			Messages:           messages,
			Resources:          resources,
			WebSocketEvents:    webSocketEvents,
			Errors:             errors,
			IsBeacon:           isBeacon,
			HasSessionUnloaded: hasSessionUnloaded,
			HighlightLogs:      highlightLogs,
			PayloadID:          payloadID,
		}})
	return size.Of(events), err
}

// PushBackendPayload is the resolver for the pushBackendPayload field.
func (r *mutationResolver) PushBackendPayload(ctx context.Context, projectID *string, errors []*customModels.BackendErrorObjectInput) (interface{}, error) {
	errorsBySecureID := map[*string][]*customModels.BackendErrorObjectInput{}
	for _, backendError := range errors {
		errorsBySecureID[backendError.SessionSecureID] = append(errorsBySecureID[backendError.SessionSecureID], backendError)
	}
	for secureID, backendErrors := range errorsBySecureID {
		var partitionKey string
		if secureID != nil {
			partitionKey = *secureID
		} else if projectID != nil {
			partitionKey = uuid.New().String()
		}
		err := r.ProducerQueue.Submit(ctx, partitionKey, &kafkaqueue.Message{
			Type: kafkaqueue.PushBackendPayload,
			PushBackendPayload: &kafkaqueue.PushBackendPayloadArgs{
				ProjectVerboseID: projectID,
				SessionSecureID:  secureID,
				Errors:           backendErrors,
			}})
		if err != nil {
			log.WithContext(ctx).WithFields(log.Fields{"project_id": projectID, "secure_id": secureID}).
				Error(e.Wrap(err, "failed to send kafka message for push backend payload."))
		}
	}
	return nil, nil
}

// PushMetrics is the resolver for the pushMetrics field.
func (r *mutationResolver) PushMetrics(ctx context.Context, metrics []*customModels.MetricInput) (int, error) {
	return r.SubmitMetricsMessage(ctx, metrics)
}

// Deprecated: MarkBackendSetup is the resolver for the markBackendSetup field. This may be used by old SDKs but is a NOOP
func (r *mutationResolver) MarkBackendSetup(ctx context.Context, projectID *string, sessionSecureID *string, typeArg *string) (interface{}, error) {
	return nil, nil
}

// AddSessionFeedback is the resolver for the addSessionFeedback field.
func (r *mutationResolver) AddSessionFeedback(ctx context.Context, sessionSecureID string, userName *string, userEmail *string, verbatim string, timestamp time.Time) (string, error) {
	err := r.ProducerQueue.Submit(ctx, sessionSecureID, &kafkaqueue.Message{
		Type: kafkaqueue.AddSessionFeedback,
		AddSessionFeedback: &kafkaqueue.AddSessionFeedbackArgs{
			SessionSecureID: sessionSecureID,
			UserName:        userName,
			UserEmail:       userEmail,
			Verbatim:        verbatim,
			Timestamp:       timestamp,
		}})

	return sessionSecureID, err
}

// Ignore is the resolver for the ignore field.
func (r *queryResolver) Ignore(ctx context.Context, id int) (interface{}, error) {
	return nil, nil
}

// Mutation returns generated1.MutationResolver implementation.
func (r *Resolver) Mutation() generated1.MutationResolver { return &mutationResolver{r} }

// Query returns generated1.QueryResolver implementation.
func (r *Resolver) Query() generated1.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
