export const anchorFeature: string
export const anchorHead: string
export const anchorImage: string
export const anchorSmall: string
export const anchorTitle: string
export const arrow: string
export const arrow1: string
export const arrow2: string
export const author: string
export const authorImage: string
export const bgPosition: string
export const bigHero: string
export const blueDiv: string
export const bodyLarge: string
export const bodySmall: string
export const buttonArrow: string
export const buttonContainer: string
export const callToActionBackground: string
export const carouselButton: string
export const carouselContainer: string
export const codeSection: string
export const codeSnippetButtons: string
export const codeSnippetCircle: string
export const codeSnippetContent: string
export const codeSnippetCopy: string
export const codeSnippetCopyIcon: string
export const codeSnippetFrame: string
export const codeSnippetIcon: string
export const codeSnippetTopbar: string
export const collaborationGraphic: string
export const collapseHeader: string
export const companies: string
export const companiesLastRow: string
export const companiesLastRowContainer: string
export const companyLogo: string
export const ctaBg: string
export const ctaContainer: string
export const ctaTitle: string
export const customerCopy: string
export const customerReel: string
export const featureContainer: string
export const featureItem: string
export const featuresColumnContainer: string
export const featuresLeftColumn: string
export const featuresRightColumn: string
export const featuresSection: string
export const footerImageLeft: string
export const footerImageRight: string
export const gradientText: string
export const gridSectionImageLeft: string
export const hero: string
export const heroBug: string
export const heroBugLeft: string
export const heroBugRight: string
export const heroImage: string
export const heroVideoWrapper: string
export const hideImage: string
export const hideMobile: string
export const hidePhone: string
export const hideVideo: string
export const highlightedText: string
export const hollowButton: string
export const imageInner: string
export const infoContainer: string
export const innerCarouselButton: string
export const innerCarouselFeature: string
export const jayImage: string
export const landingAnchorHead: string
export const landingInfoRow: string
export const mobile: string
export const mobileOnly: string
export const mobileSpacing: string
export const modalBg: string
export const modalClose: string
export const obfuscation: string
export const obfuscationHandle: string
export const obfuscationImage: string
export const ossCard: string
export const playButton: string
export const playButtonIcon: string
export const playCard: string
export const purpleDiv: string
export const reviewCard: string
export const reviewText: string
export const scaleHeight: string
export const scaleHeightWhopAndAurora: string
export const scroll: string
export const search: string
export const searchTwoHighlighters: string
export const secondaryAnchor: string
export const secondaryBackground: string
export const sectionBody: string
export const sectionCollapse: string
export const sectionImageLeft: string
export const sectionImageRight: string
export const sectionInfo: string
export const sectionSubtitle: string
export const sectionText: string
export const simpleCallToActionBackground: string
export const slider: string
export const slideTrack: string
export const snippetBeta: string
export const snippetContent: string
export const snippetDropdown: string
export const snippetDropdownContainer: string
export const snippetDropdownList: string
export const snippetDropdownValue: string
export const snippetTab: string
export const snippetTabs: string
export const solidButton: string
export const tabletGraphic: string
export const tabSelected: string
export const thumbnail: string
export const tryButtonContainer: string
export const videoModal: string
export const whiteButton: string
