mutation PushPayload(
    $session_id: ID!
    $events: ReplayEventsInput!
    $messages: String!
    $resources: String!
    $errors: [ErrorObjectInput]!
    $is_beacon: Boolean
    $has_session_unloaded: Boolean
    $highlight_logs: String
) {
    pushPayload(
        session_id: $session_id
        events: $events
        messages: $messages
        resources: $resources
        errors: $errors
        is_beacon: $is_beacon
        has_session_unloaded: $has_session_unloaded
        highlight_logs: $highlight_logs
    )
}

mutation identifySession(
    $session_id: ID!
    $user_identifier: String!
    $user_object: Any
) {
    identifySession(
        session_id: $session_id
        user_identifier: $user_identifier
        user_object: $user_object
    )
}

mutation addSessionProperties($session_id: ID!, $properties_object: Any) {
    addSessionProperties(
        session_id: $session_id
        properties_object: $properties_object
    )
}

mutation addWebVitals($session_id: ID!, $metric: WebVitalMetricInput!) {
    addWebVitals(session_id: $session_id, metric: $metric)
}

mutation addDeviceMetric($session_id: ID!, $metric: DeviceMetricInput!) {
    addDeviceMetric(session_id: $session_id, metric: $metric)
}

mutation addTrackProperties($session_id: ID!, $properties_object: Any) {
    addTrackProperties(
        session_id: $session_id
        properties_object: $properties_object
    )
}

mutation addSessionFeedback(
    $session_id: ID!
    $user_name: String
    $user_email: String
    $verbatim: String!
    $timestamp: Timestamp!
) {
    addSessionFeedback(
        session_id: $session_id
        user_name: $user_name
        user_email: $user_email
        verbatim: $verbatim
        timestamp: $timestamp
    )
}

mutation initializeSession(
    $organization_verbose_id: String!
    $enable_strict_privacy: Boolean!
    $enable_recording_network_contents: Boolean!
    $clientVersion: String!
    $firstloadVersion: String!
    $clientConfig: String!
    $environment: String!
    $id: String!
    $appVersion: String
    $session_secure_id: String
) {
    initializeSession(
        organization_verbose_id: $organization_verbose_id
        enable_strict_privacy: $enable_strict_privacy
        enable_recording_network_contents: $enable_recording_network_contents
        clientVersion: $clientVersion
        firstloadVersion: $firstloadVersion
        clientConfig: $clientConfig
        environment: $environment
        appVersion: $appVersion
        fingerprint: $id
        session_secure_id: $session_secure_id
    ) {
        id
        secure_id
        organization_id
        project_id
    }
}

# The gql codegen library requires a query in the schema, so this is just a placeholder.
# Tangentially related:
# https://github.com/dotansimha/graphql-code-generator/issues/3268
query Ignore($id: ID!) {
    ignore(id: $id)
}
