export const appBody: string
export const browserHeader: string
export const googleLogoStyle: string
export const googleText: string
export const loadingWrapper: string
export const loginForm: string
export const loginFormWrapper: string
export const loginPage: string
export const loginStateSwitcher: string
export const loginSubTitle: string
export const loginTitle: string
export const loginTitleWrapper: string
export const otherSigninText: string
export const playButtonStyle: string
export const playerPageBody: string
export const playSection: string
export const progressBar: string
export const rrwebPlayerDiv: string
export const rrwebPlayerSection: string
export const rrwebPlayerWrapper: string
export const signinWrapper: string
export const streamElement: string
export const timeSection: string
export const undoButtonStyle: string
export const undoSection: string
export const urlAddressBar: string
export const urlAddressBarWrapper: string
export const urlText: string
export const windowOptions: string
