export const active: string
export const breadcrumb: string
export const callout: string
export const calloutContent: string
export const calloutIcon: string
export const centerInner: string
export const centerSection: string
export const chevronDown: string
export const codeBlock: string
export const codeBlockTopper: string
export const codeCopyIcon: string
export const content: string
export const contentInnerBar: string
export const contentRender: string
export const contentSection: string
export const customComponent: string
export const docLink: string
export const docsCard: string
export const docsCardGroup: string
export const docsCardPara: string
export const docSelect: string
export const docSelectList: string
export const docSelectText: string
export const emptyContent: string
export const headingCopyIcon: string
export const headingSection: string
export const highlightedText: string
export const icon: string
export const inlineCodeBlock: string
export const innerParameterContainer: string
export const innerParameterHeading: string
export const leftInner: string
export const leftSection: string
export const listItem: string
export const mainWrapper: string
export const methodParameter: string
export const pageContentBullet: string
export const pageContentIcon: string
export const pageContentList: string
export const pageContentTable: string
export const pageContentTitle: string
export const pageNavigate: string
export const pageNavigateRow: string
export const pageTitle: string
export const quickStartCenterSection: string
export const quickStartSubtext: string
export const resourcesMobile: string
export const resourcesSideBar: string
export const resultTitle: string
export const rightBarWrap: string
export const rightSection: string
export const sdkCenterSection: string
export const sdkDocSection: string
export const sdkLeftColumn: string
export const sdkPageTitle: string
export const sdkRightColumn: string
export const sdkSocialItem: string
export const searchContainer: string
export const searchDiv: string
export const searchResultCard: string
export const socialItem: string
export const spinner: string
export const tocChild: string
export const tocChildren: string
export const tocChildrenContent: string
export const tocChildrenLine: string
export const tocChildrenLineWrapper: string
export const tocContents: string
export const tocIcon: string
export const tocItem: string
export const tocItemChevronClosed: string
export const tocItemCurrent: string
export const tocItemOpen: string
export const tocMenu: string
export const tocMenuLabel: string
export const tocMenuLarge: string
export const tocRow: string
