export const actionsContainer: string;
export const button: string;
export const container: string;
export const description: string;
export const dropdownPlaceholder: string;
export const metric: string;
export const name: string;
export const newMetric: string;
export const section: string;
