export const childrenContainer: string;
export const commentAuthor: string;
export const commentHeader: string;
export const commentUpdatedTime: string;
export const ellipsisButton: string;
export const endActions: string;
export const footer: string;
export const small: string;
export const textContainer: string;
