export const closeStyle: string
export const devToolsType: string
export const devToolsWrapper: string
export const emptyWrapper: string
export const option: string
export const optionsWrapper: string
export const resizeBorder: string
export const resizeContainer: string
export const resizeHandle: string
export const selected: string
export const skeletonWrapper: string
export const tabs: string
export const toggleWrapper: string
export const topBar: string
