export const box: string
export const boxSubTitle: string
export const buttonRow: string
export const email: string
export const header: string
export const inviteButton: string
export const memberCard: string
export const name: string
export const removeTeamMemberButton: string
export const role: string
export const subTitle: string
export const userDetails: string
