export const card: string
export const cardContainer: string
export const defaultIcon: string
export const directionIcon: string
export const eventContent: string
export const eventContentVerbose: string
export const eventText: string
export const eventTextSelected: string
export const eventTime: string
export const eventWrapper: string
export const firstCard: string
export const goToButton: string
export const headerRow: string
export const iconWrapper: string
export const noTimestamp: string
export const payloadContainer: string
export const payloadTitle: string
export const playIcon: string
export const selectedIcon: string
export const streamElement: string
export const tiltedIcon: string
export const timestamp: string
