source 'https://rubygems.org'

gem 'opentelemetry-sdk'
gem 'opentelemetry-exporter-otlp'
gem 'opentelemetry-instrumentation-all'
gem 'opentelemetry-semantic_conventions'
gem "debug", require: false
gem 'grpc', '~> 1.52'
