{
 "title": "Highlight.io plugin v0.2.0 features",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "service_name", "query": "highlight-io-next-frontend" },
   {
    "name": "datasource",
    "label": "Datasource",
    "query": "highlightinc-highlight-datasource"
   }
  ]
 },
 "panels": [
  {
   "title": "Logs Visualization Type",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketBy": "Timestamp",
     "bucketCount": 50,
     "column": "duration",
     "limit": 10,
     "limitAggregator": "Count",
     "limitColumn": "duration",
     "metric": "None",
     "table": "logs"
    }
   ]
  },
  {
   "title": "Query Variable Interpolation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "bucketBy": "Timestamp",
     "bucketCount": 50,
     "column": "duration",
     "limit": 10,
     "limitAggregator": "Count",
     "limitColumn": "duration",
     "metric": "Count",
     "queryText": "service_name=${service_name}",
     "table": "logs"
    }
   ]
  },
  {
   "title": "CountDistinct",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "bucketBy": "Timestamp",
     "bucketCount": 50,
     "column": "device_id",
     "limit": 10,
     "limitAggregator": "Count",
     "limitColumn": "duration",
     "metric": "CountDistinct",
     "table": "sessions"
    }
   ]
  }
 ]
}