export const googleButton: string
export const googleLogoStyle: string
export const googleText: string
export const inputContainer: string
export const loadingWrapper: string
export const loginForm: string
export const loginStateSwitcher: string
export const loginSubTitle: string
export const loginTitle: string
export const loginTitleWrapper: string
export const otherSigninText: string
export const resetPasswordText: string
