# Highlight.io services for the enterprise deployment.
x-backend-env: &backend-env
    environment:
        - ADMIN_PASSWORD
        - CLEARBIT_API_KEY
        - CLICKHOUSE_ADDRESS
        - CLICKHOUSE_DATABASE
        - CLICKHOUSE_PASSWORD
        - CLICKHOUSE_USERNAME
        - CLICKUP_CLIENT_ID
        - CLICKUP_CLIENT_SECRET
        - CONSUMER_SPAN_SAMPLING_FRACTION
        - DEMO_PROJECT_ID
        - DISCORD_BOT_SECRET
        - DISCORD_CLIENT_ID
        - DISCORD_CLIENT_SECRET
        - DOPPLER_CONFIG=enterprise
        - ENVIRONMENT
        - FIREBASE_SECRET
        - FRONT_CLIENT_ID
        - FRONT_CLIENT_SECRET
        - GITHUB_APP_ID
        - GITHUB_CLIENT_ID
        - GITHUB_CLIENT_SECRET
        - GITHUB_PRIVATE_KEY
        - GITLAB_CLIENT_ID
        - GITLAB_CLIENT_SECRET
        - GOMEMLIMIT
        - HEIGHT_CLIENT_ID
        - HEIGHT_CLIENT_SECRET
        - IN_DOCKER
        - IN_DOCKER_GO
        - JIRA_CLIENT_ID
        - JIRA_CLIENT_SECRET
        - KAFKA_ENV_PREFIX
        - KAFKA_SASL_PASSWORD
        - KAFKA_SASL_USERNAME
        - KAFKA_SERVERS
        - KAFKA_TOPIC
        - LICENSE_KEY
        - LINEAR_CLIENT_ID
        - LINEAR_CLIENT_SECRET
        - MICROSOFT_TEAMS_BOT_ID
        - MICROSOFT_TEAMS_BOT_PASSWORD
        - OBJECT_STORAGE_FS
        - ON_PREM
        - OTLP_DOGFOOD_ENDPOINT
        - OTLP_ENDPOINT
        - PSQL_DB
        - PSQL_DOCKER_HOST
        - PSQL_HOST
        - PSQL_PASSWORD
        - PSQL_PORT
        - PSQL_USER
        - REACT_APP_AUTH_MODE
        - REACT_APP_COMMIT_SHA
        - REACT_APP_FRONTEND_URI
        - REACT_APP_PRIVATE_GRAPH_URI
        - REDIS_EVENTS_STAGING_ENDPOINT
        - RELEASE
        - SESSION_FILE_PATH_PREFIX
        - SESSION_RETENTION_DAYS
        - SLACK_CLIENT_ID
        - SLACK_CLIENT_SECRET
        - SLACK_SIGNING_SECRET
        - SSL
        - TZ
        - VERCEL_CLIENT_ID
        - VERCEL_CLIENT_SECRET
        - WORKER_MAX_MEMORY_THRESHOLD
services:
    backend-session-worker:
        image: ${BACKEND_IMAGE_NAME-ghcr.io/highlight/highlight-backend:latest}
        restart: on-failure
        volumes:
            - highlight-data:/highlight-data
            - ../backend/env.enc:/build/env.enc
            - ../backend/env.enc.dgst:/build/env.enc.dgst
            - ../backend/localhostssl/server.key:/build/localhostssl/server.key
            - ../backend/localhostssl/server.crt:/build/localhostssl/server.crt
        <<: *backend-env
        container_name: backend-session-worker
        command:
            - /build/backend
            - -runtime=worker

    backend-api:
        extends: backend-session-worker
        ports:
            - '0.0.0.0:8082:8082'
        container_name: backend-api
        command:
            - /build/backend
            - -runtime=graph

    backend-public-worker-main:
        extends: backend-session-worker
        container_name: backend-public-worker-main
        command:
            - /build/backend
            - -runtime=worker
            - -worker-handler=public-worker-main

    backend-public-worker-batched:
        extends: backend-session-worker
        container_name: backend-public-worker-batched
        command:
            - /build/backend
            - -runtime=worker
            - -worker-handler=public-worker-batched

    backend-public-worker-datasync:
        extends: backend-session-worker
        container_name: backend-public-worker-datasync
        command:
            - /build/backend
            - -runtime=worker
            - -worker-handler=public-worker-datasync

    backend-public-worker-traces:
        extends: backend-session-worker
        container_name: backend-public-worker-traces
        command:
            - /build/backend
            - -runtime=worker
            - -worker-handler=public-worker-traces

    frontend:
        container_name: frontend
        image: ${BACKEND_IMAGE_NAME-ghcr.io/highlight/highlight-frontend:latest}
        restart: on-failure
        volumes:
            - ../backend/localhostssl/server.key:/etc/ssl/private/ssl-cert.key
            - ../backend/localhostssl/server.pem:/etc/ssl/certs/ssl-cert.pem
        ports:
            - '0.0.0.0:3000:3000'
            - '0.0.0.0:6006:6006'
            - '0.0.0.0:8080:8080'
        environment:
            - REACT_APP_PRIVATE_GRAPH_URI
            - REACT_APP_PUBLIC_GRAPH_URI
            - REACT_APP_FRONTEND_URI
            - SSL

volumes:
    highlight-data:
