receivers:
    otlp:
        protocols:
            grpc:
                endpoint: '0.0.0.0:4317'
            http:
                endpoint: '0.0.0.0:4318'
    fluentforward:
        endpoint: '0.0.0.0:24224'
exporters:
    otlphttp:
        endpoint: 'https://backend:8082/otel'
        compression: gzip
        tls:
            insecure_skip_verify: true
processors:
    batch:
service:
    extensions: [health_check]
    pipelines:
        traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlphttp]
        metrics:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlphttp]
        logs:
            receivers: [otlp, fluentforward]
            processors: [batch]
            exporters: [otlphttp]
extensions:
    health_check:
        endpoint: '0.0.0.0:4319'
        path: '/health/status'
