mutation MarkSessionAsViewed($id: ID!, $viewed: Boolean!) {
    markSessionAsViewed(id: $id, viewed: $viewed) {
        id
        viewed
    }
}

mutation MarkSessionAsStarred($id: ID!, $starred: Boolean!) {
    markSessionAsStarred(id: $id, starred: $starred) {
        id
        starred
    }
}

mutation CreateOrUpdateSubscription(
    $organization_id: ID!
    $plan_type: PlanType!
) {
    createOrUpdateSubscription(
        organization_id: $organization_id
        plan_type: $plan_type
    )
}

mutation markErrorGroupAsResolved($id: ID!, $resolved: Boolean!) {
    markErrorGroupAsResolved(id: $id, resolved: $resolved) {
        id
        resolved
    }
}

mutation SendEmailSignup($email: String!) {
    emailSignup(email: $email)
}

mutation AddAdminToOrganization($organization_id: ID!, $invite_id: String!) {
    addAdminToOrganization(
        organization_id: $organization_id
        invite_id: $invite_id
    )
}

mutation AddSlackIntegrationToWorkspace(
    $organization_id: ID!
    $code: String!
    $redirect_path: String!
) {
    addSlackIntegrationToWorkspace(
        organization_id: $organization_id
        code: $code
        redirect_path: $redirect_path
    )
}

mutation CreateOrganization($name: String!) {
    createOrganization(name: $name) {
        id
        name
    }
}

mutation EditOrganization($id: ID!, $name: String, $billing_email: String) {
    editOrganization(id: $id, name: $name, billing_email: $billing_email) {
        name
        billing_email
    }
}

mutation DeleteOrganization($id: ID!) {
    deleteOrganization(id: $id)
}

mutation DeleteSegment($segment_id: ID!) {
    deleteSegment(segment_id: $segment_id)
}

mutation EditSegment(
    $organization_id: ID!
    $id: ID!
    $params: SearchParamsInput!
) {
    editSegment(organization_id: $organization_id, id: $id, params: $params)
}

mutation CreateSegment(
    $organization_id: ID!
    $name: String!
    $params: SearchParamsInput!
) {
    createSegment(
        organization_id: $organization_id
        name: $name
        params: $params
    ) {
        name
        id
        params {
            user_properties {
                name
                value
            }
            excluded_properties {
                name
                value
            }
            date_range {
                start_date
                end_date
            }
            os
            browser
            visited_url
            referrer
            identified
            hide_viewed
        }
    }
}

mutation CreateSessionComment(
    $organization_id: ID!
    $admin_id: ID!
    $session_id: ID!
    $session_timestamp: Int!
    $text: String!
) {
    createSessionComment(
        organization_id: $organization_id
        admin_id: $admin_id
        session_id: $session_id
        session_timestamp: $session_timestamp
        text: $text
    ) {
        id
        timestamp
        created_at
        updated_at
        author {
            id
            name
            email
        }
        text
    }
}

mutation DeleteErrorSegment($segment_id: ID!) {
    deleteErrorSegment(segment_id: $segment_id)
}

mutation EditErrorSegment(
    $organization_id: ID!
    $id: ID!
    $params: ErrorSearchParamsInput!
) {
    editErrorSegment(
        organization_id: $organization_id
        id: $id
        params: $params
    )
}

mutation CreateErrorSegment(
    $organization_id: ID!
    $name: String!
    $params: ErrorSearchParamsInput!
) {
    createErrorSegment(
        organization_id: $organization_id
        name: $name
        params: $params
    ) {
        name
        id
        params {
            date_range {
                start_date
                end_date
            }
            os
            browser
            visited_url
            hide_resolved
        }
    }
}
