mutation MarkSessionAsViewed($id: ID!) {
    markSessionAsViewed(id: $id)
}

query GetEvents($session_id: ID!) {
    events(session_id: $session_id)
}

query GetSession($id: ID!) {
    session(id: $id) {
        os_name
        os_version
        browser_name
        browser_version
        city
        state
        postal
        user_id
        created_at
        user_object
        identifier
        fields {
            name
            value
            type
        }
    }
}
