query GetEvents($session_id: ID!) {
    events(session_id: $session_id)
}

query GetSession($id: ID!) {
    session(id: $id) {
        os_name
        os_version
        browser_name
        browser_version
        city
        state
        postal
        user_id
        created_at
        user_object
        identifier
        fields {
            name
            value
            type
        }
    }
}

query GetAdmins($organization_id: ID!) {
    admins(organization_id: $organization_id) {
        id
        name
        email
    }
}

mutation SendAdminInvite($organization_id: ID!, $email: String!) {
    sendAdminInvite(organization_id: $organization_id, email: $email)
}

query GetSessionsBETA(
    $organization_id: ID!
    $count: Int!
    $processed: Boolean!
    $params: SearchParamsInput
) {
    sessionsBETA(
        organization_id: $organization_id
        count: $count
        processed: $processed
        params: $params
    ) {
        sessions {
            id
            user_id
            identifier
            os_name
            os_version
            browser_name
            browser_version
            city
            state
            postal
            created_at
            length
            viewed
            fields {
                name
                value
                type
            }
        }
        totalCount
    }
}

query GetOrganizations {
    organizations {
        id
        name
    }
}

query GetAdmin {
    admin {
        id
        name
        email
    }
}

query GetOrganization($id: ID!) {
    organization(id: $id) {
        id
        name
        trial_end_date
        verbose_id
        billing_email
    }
}

query GetBillingDetails($organization_id: ID!) {
    billingDetails(organization_id: $organization_id) {
        plan {
            type
            quota
        }
        meter
    }
}

query GetErrorGroup($id: ID!) {
    error_group(id: $id) {
        id
        type
        organization_id
        event
        resolved
        trace {
            file_name
            line_number
            function_name
            column_number
        }
        metadata_log {
            error_id
            session_id
            timestamp
            os
            browser
            visited_url
        }
        field_group {
            name
            value
        }
    }
}

query GetErrorGroups(
    $organization_id: ID!
    $count: Int!
    $params: ErrorSearchParamsInput
) {
    error_groups(
        organization_id: $organization_id
        count: $count
        params: $params
    ) {
        error_groups {
            id
            type
            event
            resolved
            trace {
                file_name
                line_number
                function_name
                column_number
            }
            metadata_log {
                error_id
                session_id
                timestamp
            }
        }
        totalCount
    }
}

query GetMessages($session_id: ID!) {
    messages(session_id: $session_id)
}

query GetResources($session_id: ID!) {
    resources(session_id: $session_id)
}

query GetErrors($session_id: ID!) {
    errors(session_id: $session_id) {
        error_group_id
        event
        type
        url
        source
        line_number
        column_number
        trace
    }
}

query GetFieldSuggestion(
    $organization_id: ID!
    $name: String!
    $query: String!
) {
    field_suggestionBETA(
        organization_id: $organization_id
        name: $name
        query: $query
    ) {
        name
        value
    }
}

query GetErrorFieldSuggestion(
    $organization_id: ID!
    $name: String!
    $query: String!
) {
    error_field_suggestion(
        organization_id: $organization_id
        name: $name
        query: $query
    ) {
        name
        value
    }
}

query GetTrackSuggestion($organization_id: ID!, $query: String!) {
    property_suggestion(
        organization_id: $organization_id
        query: $query
        type: "track"
    ) {
        name
        value
    }
}

query GetUserSuggestion($organization_id: ID!, $query: String!) {
    property_suggestion(
        organization_id: $organization_id
        query: $query
        type: "user"
    ) {
        name
        value
    }
}

query GetSegments($organization_id: ID!) {
    segments(organization_id: $organization_id) {
        id
        name
        params {
            user_properties {
                name
                value
            }
            excluded_properties {
                name
                value
            }
            track_properties {
                name
                value
            }
            date_range {
                start_date
                end_date
            }
            length_range {
                min
                max
            }
            os
            browser
            visited_url
            referrer
            identified
            hide_viewed
        }
    }
}

query GetErrorSegments($organization_id: ID!) {
    error_segments(organization_id: $organization_id) {
        id
        name
        params {
            date_range {
                start_date
                end_date
            }
            os
            browser
            visited_url
            hide_resolved
            event
        }
    }
}

query IsIntegrated($organization_id: ID!) {
    isIntegrated(organization_id: $organization_id)
}

query UnprocessedSessionsCount($organization_id: ID!) {
    unprocessedSessionsCount(organization_id: $organization_id)
}
