export const actionsContainer: string
export const addContainer: string
export const alertStepsHeader: string
export const alertTypeSelected: string
export const cardContainer: string
export const cardContainerSelected: string
export const cardContent: string
export const cardGrid: string
export const channelSelect: string
export const checkIconContainer: string
export const description: string
export const fullBleedAlertSetupStep: string
export const icon: string
export const integrationAlert: string
export const integrationButton: string
export const notFoundMessage: string
export const saveButton: string
export const selected: string
export const selectMessage: string
export const stepDescription: string
export const stepsTitle: string
export const stepsTitleX: string
export const title: string
export const withSlackButton: string
