FROM golang:alpine as backend-builder
RUN apk update && apk add git && apk add build-base
RUN mkdir /build-backend
WORKDIR /build-backend
COPY ./backend .
RUN go mod download
RUN GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o /bin/backend
RUN (curl -Ls https://cli.doppler.com/install.sh || wget -qO- https://cli.doppler.com/install.sh) | sh
# Not specifying an entrypoint here, as this is overridden in the task definition.
