// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Session struct {
	ID                   string        `json:"id"`
	Events               []interface{} `json:"events"`
	VisitLocationDetails interface{}   `json:"visitLocationDetails"`
}
