export const arrow: string
export const arrowWrapper: string
export const contentWrapper: string
export const header: string
export const highlightText: string
export const humans: string
export const landing: string
export const landingWrapper: string
export const logoHeader: string
export const logos: string
export const modalWrapper: string
export const nav: string
export const navLink: string
export const overlayWrapper: string
export const purpleText: string
export const securityLink: string
export const securityNav: string
export const securityWrapper: string
export const subHeader: string
export const userDropdownContainer: string
