export const button: string
export const checkIcon: string
export const checkWrapper: string
export const checkWrapperCompleted: string
export const closeButton: string
export const container: string
export const enterViewport: string
export const onboardingBubblePopoverHeader: string
export const popover: string
export const stepCompleted: string
export const stepIncomplete: string
export const stepsContainer: string
export const stepsCount: string
export const tooltip: string
