export const alert: string
export const codeBlock: string
export const collapsibleWrapper: string
export const contentWrapper: string
export const editor: string
export const fillerText: string
export const functionName: string
export const lineNumber: string
export const skeleton: string
export const sourcemapActions: string
export const stackTraceCard: string
export const tooltip: string
