export const actionButtons: string
export const actionButtonsContainer: string
export const collapsible: string
export const commentDiv: string
export const commentInputContainer: string
export const commentInputDiv: string
export const deepLinked: string
export const errorLogButton: string
export const errorLogCell: string
export const errorLogDivider: string
export const errorLogItem: string
export const errorLogOverflow: string
export const errorLogsTitle: string
export const errorLogWrapper: string
export const eventText: string
export const expandButton: string
export const fieldWrapper: string
export const graphLabels: string
export const graphSection: string
export const icon: string
export const iconWrapper: string
export const intercomLink: string
export const rightButtonsContainer: string
export const section: string
export const sectionItem: string
export const sectionRow: string
export const snippetHeadingTwo: string
export const stackTraceErrorTitle: string
export const subSection: string
export const title: string
export const titleContainer: string
export const titleWithAction: string
export const titleWithMargin: string
export const triggerWrapper: string
