export const active: string
export const detailedMetric: string
export const good: string
export const goodScore: string
export const infoTooltip: string
export const metric: string
export const mirror: string
export const name: string
export const needsImprovement: string
export const needsImprovementScore: string
export const poor: string
export const poorScore: string
export const scoreIndicator: string
export const scoreVisualization: string
export const simpleMetric: string
export const units: string
export const value: string
