export const button: string
export const buttonContainer: string
export const commentAuthor: string
export const commentHeader: string
export const commentUpdatedTime: string
export const devToolsActive: string
export const devToolsButton: string
export const devToolsIcon: string
export const dropdownInner: string
export const dropdownMenu: string
export const dropdownSection: string
export const firstSegment: string
export const icon: string
export const inactive: string
export const inactiveIcon: string
export const inactiveText: string
export const indicator: string
export const indicatorParent: string
export const lastSegment: string
export const liveButton: string
export const livePlayerRail: string
export const liveShimmer: string
export const liveUserStatus: string
export const playButtonStyle: string
export const playerRail: string
export const playSection: string
export const popoverContent: string
export const popoverHeader: string
export const redoSection: string
export const segmentHover: string
export const settingsButton: string
export const settingsPopover: string
export const skipButtonStyle: string
export const skipInactivity: string
export const sliderMargin: string
export const sliderPopover: string
export const sliderPopoverDescription: string
export const sliderPopoverTime: string
export const sliderRail: string
export const sliderSegment: string
export const sliderWrapper: string
export const speedControlContainer: string
export const timeSection: string
export const toolbarLeftSection: string
export const toolbarPinnedSettings: string
export const toolbarRightSection: string
export const undoSection: string
export const verticalDivider: string
