export const appBody: string
export const browserHeader: string
export const loadingWrapper: string
export const playButtonStyle: string
export const playerPageBody: string
export const progressBar: string
export const rrwebPlayerDiv: string
export const rrwebPlayerWrapper: string
export const signinWrapper: string
export const timeSection: string
export const undoButtonStyle: string
export const undoSection: string
export const urlAddressBar: string
export const urlAddressBarWrapper: string
export const urlText: string
export const windowOptions: string
