export const categoryButton: string
export const categoryButtonActive: string
export const copyOnDark: string
export const copyOnLight: string
export const gridContainer: string
export const headerButton: string
export const innerContainer: string
export const innerGridLeft: string
export const innerGridRight: string
export const innerPopoverPanel: string
export const link: string
export const popover: string
export const popoverButton: string
export const popoverPanel: string
export const white: string
