export const copyOnDark: string
export const copyOnLight: string
export const gridContainer: string
export const featureGridContainer: string
export const gridItem: string
export const headerButton: string
export const popover: string
export const popoverButton: string
export const popoverPanel: string
export const white: string
