export const actionIcon: string
export const activityGraphContainer: string
export const avatarWrapper: string
export const backfilledIcon: string
export const bottomText: string
export const cardAnnotation: string
export const cardAnnotationContainer: string
export const compact: string
export const detailed: string
export const detailedSection: string
export const errorVersion: string
export const identifier: string
export const linkDisabled: string
export const middleText: string
export const readMarkerContainer: string
export const selected: string
export const separator: string
export const sessionCard: string
export const sessionCardAction: string
export const sessionCardContentWrapper: string
export const sessionCardWrapper: string
export const sessionTextSection: string
export const sessionTextSectionWrapper: string
export const starredIcon: string
export const starredIconWrapper: string
export const tagWrapper: string
export const topText: string
export const withLongDatetimeFormat: string
