export const animation: string
export const button: string
export const buttonV2: string
export const dotContainer: string
export const emptyStateContainer: string
export const filtersButton: string
export const filtersContainer: string
export const iconContainer: string
export const iconContainerV2: string
export const list: string
export const noResultsMessage: string
export const notification: string
export const notificationBody: string
export const notificationIconContainer: string
export const notificationStartColumn: string
export const personalNotificationAlert: string
export const popover: string
export const popoverTitle: string
export const search: string
export const searchContainer: string
export const searchIcon: string
export const section: string
export const tabBarExtraContent: string
export const tabs: string
export const tagsSelect: string
export const timestamp: string
export const title: string
export const titleSuffix: string
