export const advertisedFeature: string
export const advertisedFeaturesWrapper: string
export const billingFrequency: string
export const billingPlanCard: string
export const billingPlanPrice: string
export const billingPlanTitle: string
export const button: string
export const currentPlan: string
export const intervalToggle: string
export const intervalToggleContainer: string
