export const antDropdown: string
export const antDropdownMenuItem: string
export const antPickerDropdown: string
export const antPickerInput: string
export const antPickerSuffix: string
export const antPopoverInnerContent: string
export const antTableBody: string
export const antTableCell: string
export const antTabs: string
export const antTabsBottom: string
export const antTabsContent: string
export const antTabsInkBar: string
export const antTabsNav: string
export const antTabsNavWrap: string
export const antTabsTab: string
export const antTabsTabActive: string
export const antTabsTabBtn: string
export const antTabsTop: string
export const app: string
export const collapsible: string
export const collapsibleContentInner: string
export const rcSlider: string
export const replayerWrapper: string
