export const avatar: string
export const avatarWrapper: string
export const backfillShown: string
export const backfillUserIcon: string
export const blurred: string
export const deviceDetails: string
export const enableClearbit: string
export const enhancedBio: string
export const enhancedLinksGrid: string
export const enhancedName: string
export const enhancedSocial: string
export const enhancedSocialText: string
export const enhancedTextSection: string
export const expandArrow: string
export const headerWrapper: string
export const skeletonWrapper: string
export const socialIcon: string
export const socialIcons: string
export const starIconWrapper: string
export const starredIcon: string
export const tagEllipsis: string
export const tooltip: string
export const unstarredIcon: string
export const userAvatarWrapper: string
export const userBox: string
export const userDetailsSection: string
export const userEnhanced: string
export const userIdentifier: string
export const userIdHeader: string
export const userIdSubHeader: string
export const userInfoWrapper: string
export const userMainSection: string
export const userProfile: string
export const userText: string
export const viewAllSessionsButton: string
