export const authorDiv: string
export const avatar: string
export const caseBackLink: string
export const caseContent: string
export const caseCustomerDetails: string
export const caseDetailsBlock: string
export const caseDetailsBody: string
export const caseDetailsLogo: string
export const caseDetailsSecitonText: string
export const caseOverline: string
export const casePageLink: string
export const casePageLinks: string
export const caseTitle: string
export const companyDiv: string
export const companyLogo: string
export const customerCard: string
export const detailsLayout: string
export const reviewGrid: string
