export const allCustomersGrid: string
export const allCustomersLogo: string
export const cardReadCaseButton: string
export const caseCard: string
export const caseCardQuote: string
export const caseDetails: string
export const caseList: string
export const caseListLayout: string
export const caseListTitle: string
export const companyCaseLogo: string
export const leftQuote: string
export const limeAccent: string
export const rightQuote: string
export const thumbnail: string
