export const box: string
export const button: string
export const cardForm: string
export const inputLabel: string
export const promoCodeToggle: string
export const subTitle: string
export const switchWorkspace: string
export const title: string
export const workspaceCount: string
