export const anchorFeature: string
export const buttonContainer: string
export const divider: string
export const docsButton: string
export const featureBox: string
export const featureBoxIcon: string
export const featureBoxText: string
export const highlightedBadge: string
export const hollowButton: string
export const infoContainer: string
export const infoTitle: string
export const snippet: string
export const subtleBadge: string
