export const chartHeaderWrapper: string;
export const dashboard: string;
export const dashboardBody: string;
export const dashboardWrapper: string;
export const filtersContainer: string;
export const graphSection: string;
export const section: string;
export const subTitle: string;
export const tooltip: string;
