export const actionIcon: string
export const avatarWrapper: string
export const bottomText: string
export const errorBar: string
export const errorBarBase: string
export const errorBarDiv: string
export const errorCard: string
export const errorCardAction: string
export const errorCardContentWrapper: string
export const errorCardWrapper: string
export const errorTextSection: string
export const errorTextSectionWrapper: string
export const errorTextWrapper: string
export const feedContent: string
export const feedWrapper: string
export const fixedContent: string
export const hoverBorderLeft: string
export const hoverBorderOn: string
export const hoverBorderRight: string
export const ignored: string
export const mainUserInput: string
export const middleText: string
export const open: string
export const readMarker: string
export const readMarkerContainer: string
export const resolved: string
export const resultCount: string
export const tagWrapper: string
export const topText: string
export const userInputWrapper: string
