// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type BackendErrorObjectInput struct {
	SessionID  string    `json:"session_id"`
	RequestID  string    `json:"request_id"`
	Event      string    `json:"event"`
	Type       string    `json:"type"`
	URL        string    `json:"url"`
	Source     string    `json:"source"`
	StackTrace string    `json:"stackTrace"`
	Timestamp  time.Time `json:"timestamp"`
	Payload    *string   `json:"payload"`
}

type ErrorObjectInput struct {
	Event        string             `json:"event"`
	Type         string             `json:"type"`
	URL          string             `json:"url"`
	Source       string             `json:"source"`
	LineNumber   int                `json:"lineNumber"`
	ColumnNumber int                `json:"columnNumber"`
	StackTrace   []*StackFrameInput `json:"stackTrace"`
	Timestamp    time.Time          `json:"timestamp"`
	Payload      *string            `json:"payload"`
}

type ReplayEventsInput struct {
	Events []interface{} `json:"events"`
}

type StackFrameInput struct {
	FunctionName *string       `json:"functionName"`
	Args         []interface{} `json:"args"`
	FileName     *string       `json:"fileName"`
	LineNumber   *int          `json:"lineNumber"`
	ColumnNumber *int          `json:"columnNumber"`
	IsEval       *bool         `json:"isEval"`
	IsNative     *bool         `json:"isNative"`
	Source       *string       `json:"source"`
}
