// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type ErrorObjectInput struct {
	Event        string        `json:"event"`
	Type         string        `json:"type"`
	URL          string        `json:"url"`
	Source       string        `json:"source"`
	LineNumber   int           `json:"lineNumber"`
	ColumnNumber int           `json:"columnNumber"`
	Trace        []interface{} `json:"trace"`
	Timestamp    time.Time     `json:"timestamp"`
	Payload      *string       `json:"payload"`
}

type ReplayEventsInput struct {
	Events []interface{} `json:"events"`
}
