export const actionButton: string
export const eventIdentifier: string
export const eventTypeIcon: string
export const eventTypeRow: string
export const infoPanel: string
export const infoPanelCounter: string
export const isHidden: string
export const leftActionIcon: string
export const rightActionIcon: string
export const rightCounter: string
export const selectedTypeName: string
export const timelinePopoverContent: string
export const timelinePopoverDetails: string
export const timelinePopoverHeader: string
export const transitionIcon: string
