export const container: string;
export const dateRangePicker: string;
export const dateRangePickerContainer: string;
export const dropdownPlaceholder: string;
export const gridContainer: string;
export const isEditing: string;
export const metric: string;
export const newMetric: string;
export const section: string;
