AllCops:
    TargetRubyVersion: 3.0
    EnabledByDefault: true

Style/FrozenStringLiteralComment:
    Enabled: false

Style/Documentation:
    Enabled: false

Metrics/MethodLength:
    Enabled: false

Metrics/CyclomaticComplexity:
    Enabled: false

Metrics/PerceivedComplexity:
    Enabled: false

Naming/MethodParameterName:
    Enabled: false

Metrics/AbcSize:
    Enabled: false

Metrics/ClassLength:
    Enabled: false
