AllCops:
    TargetRubyVersion: 3.0

Style/FrozenStringLiteralComment:
    Enabled: false

Style/Documentation:
    Enabled: false

Metrics/MethodLength:
    Enabled: false

Metrics/CyclomaticComplexity:
    Max: 8

Naming/MethodParameterName:
    Enabled: false

Metrics/AbcSize:
    Enabled: false

Metrics/ClassLength:
    Enabled: false
