source "https://rubygems.org"

# Specify your gem's dependencies in highlight.gemspec
gemspec

gem "rake", "~> 12.0"
gem "minitest", "~> 5.0"

# Gemfile
group :development do
  gem 'rubocop', require: false
end