export const card: string
export const cardContent: string
export const cardImage: string
export const cardInfo: string
export const cardInfoTitle: string
export const cardInfoWrapper: string
export const cards: string
export const link: string
export const sourceLink: string
export const youtubeLink: string
