export const container: string;
export const dateOption: string;
export const dateOptions: string;
export const dateOptionsContainer: string;
export const datepicker: string;
export const datepickerContainer: string;
export const input: string;
export const label: string;
export const open: string;
