declare const styles: {
  readonly "streamElement": string;
  readonly "playButtonStyle": string;
  readonly "appBody": string;
  readonly "windowOptions": string;
  readonly "urlText": string;
  readonly "urlAddressBarWrapper": string;
  readonly "urlAddressBar": string;
  readonly "playerPageBody": string;
  readonly "loadingWrapper": string;
  readonly "rrwebPlayerSection": string;
  readonly "rrwebPlayerWrapper": string;
  readonly "browserHeader": string;
  readonly "rrwebPlayerDiv": string;
  readonly "progressBar": string;
  readonly "playSection": string;
  readonly "undoSection": string;
  readonly "timeSection": string;
  readonly "undoButtonStyle": string;
  readonly "loginFormWrapper": string;
  readonly "loginForm": string;
  readonly "loginTitleWrapper": string;
  readonly "loginStateSwitcher": string;
  readonly "loginTitle": string;
  readonly "loginSubTitle": string;
  readonly "loginPage": string;
  readonly "otherSigninText": string;
  readonly "googleLogoStyle": string;
  readonly "googleText": string;
  readonly "signinWrapper": string;
};
export = styles;

