export const antDropdownMenu: string
export const antDropdownMenuItem: string
export const antDropdownMenuSubmenuTitle: string
export const antMessage: string
export const antMessageNoticeContent: string
export const antModalMask: string
export const antSelectItem: string
export const antSelectItemOptionActive: string
export const antSelectItemOptionDisabled: string
export const antSelectItemOptionSelected: string
export const antSkeletonContent: string
export const antSkeletonParagraph: string
export const antSkeletonTitle: string
export const antSlider: string
export const antSliderDot: string
export const antSliderHandle: string
export const antSliderHandleDragging: string
export const antSliderRail: string
export const antSliderTrack: string
export const antSwitchChecked: string
export const antTooltip: string
export const antTooltipInner: string
export const antTooltipOpen: string
export const atomOverlay: string
export const blob: string
export const cssFoqpf7: string
export const pulse: string
