#!/bin/sh

export REACT_ENV_COMMIT_SHA=$(git rev-parse HEAD)
doppler run -- docker build --build-arg "
SENDGRID_API_KEY=$SENDGRID_API_KEY
SLACK_CLIENT_ID=$SLACK_CLIENT_ID
SLACK_CLIENT_SECRET=$SLACK_CLIENT_SECRET
TURBO_TOKEN=$TURBO_TOKEN
REACT_APP_COMMIT_SHA=$REACT_APP_COMMIT_SHA
TURBO_TEAM=$TURBO_TEAM
" -t highlight_local -f Dockerfile.local .
