export const accomodateBanner: string
export const demoLink: string
export const error: string
export const homeLink: string
export const logoWrapper: string
export const productHunt: string
export const quicksearchWrapper: string
export const trialCloseStyle: string
export const trialLink: string
export const trialTimeText: string
export const trialWrapper: string
