export const button: string
export const demoLink: string
export const error: string
export const homeLink: string
export const maintenance: string
export const productHunt: string
export const trialLink: string
export const trialTimeText: string
export const trialWrapper: string
export const youtube: string
