# options for analysis running
run:
    timeout: 2m

# output configuration options
output:
    # sorts results by: filepath, line and column
    sort-results: true

linters:
    enable:
        - deadcode
        - errcheck
        - gosimple
        - govet
        - ineffassign
        - staticcheck
        - structcheck
        - typecheck
        - unused
        - varcheck

# all available settings of specific linters
linters-settings:
    staticcheck:
        checks: ['all']
