# options for analysis running
run:
    timeout: 2m

# output configuration options
output:
    # sorts results by: filepath, line and column
    sort-results: true

linters:
    enable:
        - errcheck
        - gosimple
        - govet
        - ineffassign
        - typecheck
        - unused
        - depguard
        - exhaustruct
