# options for analysis running
run:
    timeout: 2m

# output configuration options
output:
    # sorts results by: filepath, line and column
    sort-results: true

linters:
    # enable all linters
    enable:
        - errcheck
        - gosimple
        - govet
        - ineffassign
        - staticcheck
        - typecheck
        - unused
        - depguard
        - exhaustruct

# all available settings of specific linters
linters-settings:
    staticcheck:
        checks: ['all']

    depguard:
        rules:
            main:
                list-mode: lax
                deny:
                    - pkg: 'log'
                      desc: 'logging is allowed only by github.com/sirupsen/logrus'
