export const goToButton: string
export const goToButtonContainer: string
export const hover: string
export const icon: string
export const iconContainer: string
export const popoverContent: string
export const rageClick: string
export const table: string
export const title: string
