export const adminText: string
export const avatarContainer: string
export const commentLink: string
export const email: string
export const longValue: string
export const noResultsMessage: string
export const slackLogo: string
export const slackLogoContainer: string
export const suggestionContainer: string
export const suggestionHeader: string
