export const adminText: string
export const avatarContainer: string
export const commentText: string
export const email: string
export const longValue: string
export const mentionedUser: string
export const noResultsMessage: string
export const slackLogo: string
export const slackLogoContainer: string
export const suggestionContainer: string
export const suggestionHeader: string
