export const mentions: string
export const mentionsControl: string
export const mentionsHighlighter: string
export const mentionsInput: string
export const mentionsMention: string
export const mentionsMultiLine: string
export const mentionsSingleLine: string
export const mentionsSuggestionsItem: string
export const mentionsSuggestionsItemFocused: string
export const mentionsSuggestionsList: string
