export const alignCenter: string
export const alignEnd: string
export const alignStart: string
export const large: string
export const medium: string
export const small: string
export const space: string
export const verticalDirection: string
export const wrap: string
export const xLarge: string
export const xSmall: string
export const xxLarge: string
export const xxSmall: string
