export const canvasNetworkWrapper: string
export const current: string
export const currentIndicator: string
export const failedResource: string
export const filterContainer: string
export const justifyEnd: string
export const nameSection: string
export const networkColumn: string
export const networkRow: string
export const networkStreamWrapper: string
export const networkTableWrapper: string
export const networkTimestampGrid: string
export const networkTimingColumn: string
export const networkTimingHeader: string
export const networkTopBar: string
export const noDataContainer: string
export const optionsContainer: string
export const optionsWrapper: string
export const resourcePageWrapper: string
export const rightAlign: string
export const showingDetails: string
export const timingBar: string
export const timingBarEmptySection: string
export const timingBarWrapper: string
export const typeSection: string
export const virtuoso: string
export const waterfall: string
