export const contentContainer: string;
export const detailPanel: string;
export const dragHandle: string;
export const dragHandleWrapper: string;
export const header: string;
export const hidden: string;
export const resizeContainer: string;
export const title: string;
export const toggleButton: string;
