export const actionIcon: string
export const bottomText: string
export const errorCard: string
export const errorCardAction: string
export const errorCardWrapper: string
export const errorTextSection: string
export const errorTextSectionWrapper: string
export const errorTextWrapper: string
export const feedContent: string
export const feedItems: string
export const feedLine: string
export const feedWrapper: string
export const filtersContainer: string
export const fixedContent: string
export const hasScrolled: string
export const ignored: string
export const middleText: string
export const open: string
export const readMarker: string
export const readMarkerContainer: string
export const resolved: string
export const resultCount: string
export const selected: string
export const topText: string
