export const embla: string
export const emblaButton: string
export const emblaButtonNext: string
export const emblaButtonPrev: string
export const emblaButtonSvg: string
export const emblaContainer: string
export const emblaSlide: string
export const emblaSlideImg: string
export const emblaSlideInner: string
export const emblaViewport: string
export const isDraggable: string
export const isDragging: string
export const reactCollapseCollapse: string
export const slickActive: string
export const slickDots: string
export const slickInitialized: string
export const slickList: string
export const slickSlide: string
export const slickSlider: string
