declare const styles: {
  readonly "test": string;
  readonly "sessionsBody": string;
  readonly "sessionsSection": string;
  readonly "sessionsHeader": string;
  readonly "timesIcon": string;
  readonly "loadingDiv": string;
  readonly "searchIcon": string;
  readonly "searchIconWrapper": string;
  readonly "searchInputSection": string;
  readonly "optionsTitle": string;
  readonly "optionInput": string;
  readonly "optionKey": string;
  readonly "optionInputWrapper": string;
  readonly "optionsRow": string;
  readonly "optionsKey": string;
  readonly "dropdownTitle": string;
  readonly "dropdownSection": string;
  readonly "optionsValue": string;
  readonly "optionsSection": string;
  readonly "dropdownDivider": string;
  readonly "dropdown": string;
  readonly "searchBar": string;
  readonly "searchInput": string;
  readonly "mainInputDiv": string;
  readonly "sessionCard": string;
  readonly "sessionTextSection": string;
  readonly "sessionTextWrapper": string;
  readonly "playButton": string;
  readonly "regTitle": string;
  readonly "blueTitle": string;
  readonly "regSubTitle": string;
};
export = styles;

