export const callToAction: string
export const cellWithTooltip: string
export const chart: string
export const configurationContainer: string
export const configureButton: string
export const emptyContainer: string
export const frequencyGraphEmptyMessage: string
export const innerChart: string
export const integrationAlert: string
export const intercomButton: string
export const nameCell: string
export const primary: string
export const subTitleContainer: string
