name: Client
on:
    push:
        paths:
            - 'firstload/**'
            - 'client/**'
            - '.github/workflows/client.yml'
jobs:
    client:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org
            - name: Install main dependencies
              run: cd client && yarn install
            - name: Runs linting
              run: cd client && yarn lint
            - name: Build Bundle
              run: cd client && yarn build
