name: Firstload
on:
    push:
        paths:
            - 'firstload/**'
            - '.github/workflows/firstload.yml'
jobs:
    firstload:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 16.14.2
                  registry-url: https://registry.npmjs.org
            - name: Install main dependencies
              run: cd firstload && yarn install
            - name: Install other dependencies
              run: cd client && yarn install
            # - name: Run tests
            #   run: cd firstload && yarn test
            - name: Build Bundle
              run: cd firstload && yarn build
            - name: Confirm new version
              run: cd firstload && python3 ../scripts/compare.py -s firstload
            - name: Publish
              if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/beta'
              run: cd firstload && yarn publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
