name: 'Rust SDK'

on:
    push:
        branches: ['main']
    pull_request:
        types: [opened, reopened, synchronize, assigned, review_requested]
        paths:
            - 'sdk/highlight-rust/**'
            - '.github/workflows/rust-sdk.yml'

permissions:
    checks: write

defaults:
    run:
        working-directory: ./sdk/highlight-rust

concurrency: ${{ github.workflow }}-${{ github.ref }}
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'
        defaults:
            run:
                working-directory: ./sdk/highlight-rust
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Install Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true

            - name: Build crates
              uses: katyo/publish-crates@v2
              with:
                  path: ./sdk/highlight-rust/
                  dry-run: true
    publish:
        name: Publish
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        defaults:
            run:
                working-directory: ./sdk/highlight-rust
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Install Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  override: true

            - name: Publish crates
              uses: katyo/publish-crates@v2
              with:
                  path: ./sdk/highlight-rust/
                  registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
