name: Source Map Uploader
on:
    push:
        paths:
            - 'experiments/sourcemap-uploader/**'
            - '.github/workflows/source-map-uploader.yml'
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 15.11.0
                  registry-url: https://registry.npmjs.org
            - name: Install main dependencies
              run: cd experiments/sourcemap-uploader && yarn install
            - name: Publish
              # if: github.ref == 'refs/heads/master'
              run: cd experiments/sourcemap-uploader && yarn publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
