export const accountIcon: string
export const accountIconWrapper: string
export const appBody: string
export const browserHeader: string
export const center: string
export const emptySessionCard: string
export const gridBackground: string
export const header: string
export const headerLink: string
export const intercomLink: string
export const loadingWrapper: string
export const manuallyStoppedMessageContainer: string
export const panelShown: string
export const panelToggleButton: string
export const panelToggleButtonLeft: string
export const panelToggleButtonRight: string
export const playerBody: string
export const playerPageBody: string
export const progressBar: string
export const rrwebPlayerWrapper: string
export const signinWrapper: string
export const urlAddressBar: string
export const urlAddressBarWrapper: string
export const urlText: string
export const windowOptions: string
export const withLeftPanel: string
