export const backdrop: string
export const container: string
export const cta: string
export const description: string
export const disabled: string
export const elevatedCard: string
export const elevatedCardMotion: string
export const emptyDescription: string
export const emptyTitle: string
export const kbd: string
export const kbdContainer: string
export const searchIcon: string
export const shortcutContainer: string
export const suggestionButton: string
export const symbol: string
export const titleContainer: string
